### ISSUE TITLE
Getting below error for lock action

### ISSUE THREAD

**Issue by root-edu** [github/lock#14]
Run github/lock@v1.3.0
Error: HttpError: Not Found
    at /home/runner/work/_actions/github/lock/v1.3.0/webpack:/lock-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/root-edu/nodejs-app/actions/runs/4531885799/jobs/7982578990#step:2:10)6:5)
    at run (/home/runner/work/_actions/github/lock/v1.3.0/webpack:/lock-action/src/main.js:182:1)
HttpError: Not Found
    at /home/runner/work/_actions/github/lock/v1.3.0/webpack:/lock-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at run (/home/runner/work/_actions/github/lock/v1.3.0/webpack:/lock-action/src/main.js:182:1)
Error: Not Found

**Comment by root-edu** [comment]
name: lock-or-unlock

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  lock-or-unlock:
    runs-on: ubuntu-latest
    steps:
      # Lock or Unlock via a comment (ex: .lock or .unlock)
      - uses: github/lock@v1.3.0
        id: lock
    #    with:
        #  github_token: ${{ github.token }}

**Comment by root-edu** [comment]
`name: lock-or-unlock

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  lock-or-unlock:
    runs-on: ubuntu-latest
    steps:
      # Lock or Unlock via a comment (ex: .lock or .unlock)
      - uses: github/lock@v1.3.0
        id: lock
    #    with:
        #  github_token: ${{ github.token }}`

**Comment by GrantBirki** [comment]
@root-edu I would try upgrading to `github/lock@v2.0.0` and see if that resolves the issue. There has been many bug fixes and features added since `v1.3.0`. Let me know what your results are!

Also, you don't need to pass in `github_token` as it will added for you by default so you can remove that line to clean up your workflow a big :smiley:

**Comment by GrantBirki** [comment]
It should also be noted that there is currently on on-going incident on GitHub -> https://www.githubstatus.com/incidents/52z0j6phhnjs

The incident may be the cause of your error and it might not be related to this Action at all. Please also confirm if this error goes away when the GitHub incident resolves.

**Comment by GrantBirki** [comment]
I'm fairly sure this was related to the Actions incident at the time. If you are still seeing this issue, please feel free to re-open this issue and ping me @root-edu
